[package]
name = "viewer"
version = "0.1.0"
authors = ["John Barker <jebarker@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "*"
bevy_webgl2 = {version = "0.5"}
tracing = "*"
tracing-wasm = "*"
wasm-bindgen = "*"
winit = {version = "0.24", features = ["web-sys"]}
web-sys = "*"

[dependencies.bevy]
version = "0.5"
default-features = false
features = ["bevy_winit", "bevy_gltf", "render", "png"]

# See comment here https://github.com/rust-windowing/winit/pull/1827#issuecomment-928898773
# This ensures mouse move events work
[patch.crates-io]
winit = { git  = "https://github.com/TotalKrill/winit.git", branch = "dummy-feature", version = "0.24" }

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
opt-level = 'z'
