[package]
name = "viewer"
version = "0.1.0"
authors = ["John Barker <jebarker@gmail.com>"]
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "*"
tracing = "*"
tracing-wasm = "*"
wasm-bindgen = "*"
winit = "*"
web-sys = "*"

[dependencies.bevy]
version = "0.7"
default-features = false
features = ["bevy_winit", "bevy_gltf", "render", "png"]

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
opt-level = "z"
