[package]
name = "viewer"
version = "0.1.0"
authors = ["John Barker <jebarker@gmail.com>"]
edition = "2018"
# See FIXME in top level Cargo.toml
# workspace = ".."

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "*"
js-sys = "*"
nalgebra = "*"
tracing = "*"
tracing-wasm = "*"
wasm-bindgen = "*"

[dependencies.web-sys]
version = "*"
features = [
  'console',
  'CssStyleDeclaration',
  'Document',
  'DomWindowResizeEventDetail',
  'Element',
  'Event',
  'EventTarget',
  'HtmlCanvasElement',
  'HtmlElement',
  'HtmlImageElement',
  'HtmlInputElement',
  'InputEvent',
  'MouseEvent',
  'Node',
  'Touch',
  'TouchEvent',
  'TouchList',
  'WebGlBuffer',
  'WebGlFramebuffer',
  'WebGlProgram',
  'WebGlRenderbuffer',
  'WebGl2RenderingContext',
  'WebGlShader',
  'WebGlTexture',
  'WebGlUniformLocation',
  'WebGlVertexArrayObject',
  'WheelEvent',
  'Window',
]
